### ISSUE TITLE
Where are the datasets?

### ISSUE THREAD

**Issue by 4insu** [trainindata/feature-engineering-for-time-series-forecasting#71]
I've bought your course but the dataset for air quality is nowhere to be found. I have checked Datasets folder but there's only .gitkeep.

**Comment by solegalli** [comment]
Guidelines to obtain the dataset in this notebook: https://github.com/trainindata/feature-engineering-for-time-series-forecasting/blob/main/01-Create-Datasets/03-create-air-quality-dataset.ipynb

**Comment by solegalli** [comment]
More generally, all notebooks with guidelines to create the various datasets are in this folder: https://github.com/trainindata/feature-engineering-for-time-series-forecasting/tree/main/01-Create-Datasets
